name: Update Signboard

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-signboard:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper git operations
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Create required directories
        run: |
          mkdir -p static
          mkdir -p images
          
      - name: Copy template files
        run: |
          cp signboard-cards.js static/cards.js
          cp signboard-styles.css static/styles.css
          cp responsive-styles.css static/responsive.css
          
      - name: Update signboard content
        run: python signboard.py --test --github
          
      - name: Configure Git
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
      - name: Commit and push if changed
        run: |
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update signboard content [skip ci]" && git push)
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          force_orphan: true
          exclude_assets: '**.py,**.md,requirements.txt,.gitignore'
