name: Update Signboard
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/30 * * * *'  # Fixed cron syntax
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-signboard:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Add permissions for GitHub Pages deployment
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper git operations
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Setup deployment directory
        run: |
          # Create a clean deployment directory
          mkdir -p deploy
          mkdir -p deploy/static  # Changed to match your HTML structure
          mkdir -p deploy/images
          
      - name: Copy assets for deployment
        run: |
          # Copy the index.html file
          cp index.html deploy/
          
          # Copy all static files (CSS and JS)
          cp -r static/* deploy/static/
          
          # Copy images
          cp -r assets/cards/* deploy/images/

         - name: Run signboard update
           run: |
             python app/run_signboard --test
        
      - name: Configure Git
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          publish_branch: gh-pages
          force_orphan: true