name: Update Signboard

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-signboard:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper git operations
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Setup directory structure
        run: |
          mkdir -p static/css
          mkdir -p static/js
          mkdir -p static/images
          mkdir -p assets/cards
          mkdir -p data
          mkdir -p templates/components
          
      - name: Copy static assets
        run: |
          # Copy CSS files
          cp static/css/base.css static/css/
          cp static/css/components.css static/css/
          cp static/css/responsive.css static/css/
          
          # Copy JavaScript files
          cp static/js/cards.js static/js/
          
          # Copy card images
          cp -r assets/cards/* static/images/
          
          # Copy XML data files
          cp data/card_content.xml data/
          cp data/updates.xml data/
          
          # Copy templates
          cp templates/index.html templates/
          cp -r templates/components/* templates/components/
          
      - name: Run signboard update
        run: |
          python -m app.run_signboard --test
        
      - name: Configure Git
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
      - name: Commit and push if changed
        run: |
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update signboard content [skip ci]" && git push)
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./static  # Deploy only the static directory
          publish_branch: gh-pages
          force_orphan: true
          exclude_assets: |
            **.py
            **.pyc
            **/__pycache__
            **.md
            requirements.txt
            .gitignore
            tests/
